banking/urls.py
from django.urls import path, include
from .import views
app_name = 'banking'

urlpatterns = [

    path('', views.home, name='home'),
    path('register/', views.registerAccount, name='register',),
    path('user-details/', views.user_details, name='user_details',),
    path('transfer/', views.transfer, name="transfer"),
    path('transfer_history/', views.transfer_history, name='transfer_history'),
]

simple_banking_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('banking.urls'))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

banking/models.py
from django.db import models

# Create your models here.


class registerUser(models.Model):
    name = models.CharField(max_length=200, blank=False)
    email = models.EmailField(blank=False, unique=True, max_length=200)
    balance = models.IntegerField(blank=False)
    user_id = models.AutoField(primary_key=True)

    def __str__(self):
        return self.email


class transferAmount(models.Model):
    sender = models.EmailField()
    receiver = models.EmailField()
    transfer_amount = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sender + self.receiver

banking/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound
from .models import registerUser, transferAmount
# Create your views here.


def home(request):
    if request.method == 'GET':
        emails = registerUser.objects.only('email')
        print(emails)

    return render(request, 'banking/home.html', context={'emails': emails})


def registerAccount(request):

    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        balance = request.POST.get('balance')
        if registerUser.objects.filter(email=email).exists():
            return HttpResponse('<h1>Your email is already in our list of users to be notified.Try a new email</h1>')
        else:
            user = registerUser()
            user.name = name
            user.balance = balance
            user.email = email
            user.save()
            print(user.name, user.email)
    return render(request, 'banking/register.html')


def user_details(request):
    users = registerUser.objects.all()
    print(users)
    return render(request, 'banking/user_details.html', context={'users': users})


def transfer(request):
    # if request.method == 'GET':
    #     email = registerUser.objects.only('email')
    #     print(email)
    if request.method == 'POST':
        senderEmail = request.POST.get('senderEmail')
        receiverEmail = request.POST.get('receiverEmail')
        transferBalance = request.POST.get('transferBalance')
        print(senderEmail, receiverEmail, transferBalance)
        senderPreviousBalance = registerUser.objects.get(
            email=senderEmail).balance
        receiverPreviousBalance = registerUser.objects.get(
            email=receiverEmail).balance
        print(senderPreviousBalance, receiverPreviousBalance)

        if int(senderPreviousBalance) >= int(transferBalance):
            updateSenderBalance = int(
                senderPreviousBalance)-int(transferBalance)
            updateReceiverBalance = int(
                receiverPreviousBalance)+int(transferBalance)
            print(updateSenderBalance, updateReceiverBalance)

            # transaction history
            history = transferAmount(
                sender=senderEmail, receiver=receiverEmail, transfer_amount=int(transferBalance))
            history.save()
            # print(history.__dict__)
            # history = transferAmount()
            # history.sender = senderEmail
            # history.receiver = receiverEmail
            # history.transfer_amount = int(transferBalance)
            # history.save()

            # update balance
            registerUser.objects.filter(
                email=senderEmail).update(balance=updateSenderBalance)
            registerUser.objects.filter(
                email=receiverEmail).update(balance=updateReceiverBalance)

    return render(request, 'banking/home.html', )


def transfer_history(request):
    history = transferAmount.objects.all()
    print("This is History of Transfer", history)

    return render(request, 'transfer_history.html', context={'transfer_history': history})

templates/banking/home.html
{% extends "base.html" %}

{% block title_block %}
{{title}}
{% endblock %}



{% block body_block %}

{% include "navbar.html"%}

<section class="welcome  p-2" style="background-color: #EAF0F1;">
    <div class="row">
        <div class="col-md-6 text-center my-auto">
            <h2>Welcome to</h2>
            <h1 class="fw-bold" style="color:#317E2E;">BANGLADESH BANK</h1>
        </div>
        <div class="col-md-6">

            <img class="img-fluid" src="/media/bank.jpg">
        </div>
    </div>
</section>

<section class="main text-center py-5">
    <u>
        <h1 class="fw-bold" style="">CHOOSE AN OPTION</h1>
    </u>

    <div class="transfer my-5">

        <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Money Transfer
        </button>


    </div>

    <div class="transfer my-5">
        <a href="{% url 'banking:transfer_history' %}"> <button type="button" class="btn btn-outline-success">View
                Transfer History</button></a>

    </div>
</section>


<!-- form section -->

<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Amount Transfer</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action={% url 'banking:transfer' %} method="POST">

                    {% csrf_token %}
                    <h1><b>Transfer Amount</b></h1>


                    <div class="form-group">
                        <label for="email">Sender Email Address:</label>
                        <select type="email" class="form-control" id="email" name="senderEmail">
                            <option disabled selected>
                                Sender Email
                            </option>

                            {% for email in emails %}
                            <option>
                                {{email.email}}
                            </option>

                            {% endfor %}

                        </select>
                    </div>
                    <div class="form-group">
                        <label for="email">Receiver Email Address:</label>
                        <select type="email" class="form-control" id="email" name="receiverEmail">
                            <option disabled selected>
                                Receiver Email
                            </option>

                            {% for email in emails %}
                            <option>
                                {{email.email}}
                            </option>

                            {% endfor %}

                        </select>
                    </div>

                    <div class="form-group">
                        <label for="amount">Transfer Amount:</label>
                        <input type="number" class="form-control" id="balance" name="transferBalance"
                            placeholder="Enter Balance Amount">
                    </div>



                    <br>

                    <button type="submit" class="btn btn-primary">Send</button>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>




{% endblock %}

templates/banking/navbar.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <title>{% block title_block %} {% endblock %}</title>
    {% block css_block %}
    <style>
        ul {
            margin-left: auto !important;
            margin-right: auto !important;

        }

        li {
            padding: 5px 50px !important;
        }
    </style>

    {% endblock %}
</head>

<body>
    <div class="container-fluid ">

        <nav class="navbar navbar-expand-md bg-light navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a href="#" class="nav-link">Bangladesh Bank</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">

                <li class="nav-item">
                    <a href="#" class="nav-link">Demo</a>
                </li>


                <li class="nav-item">
                    <a href="#" class="nav-link"></a>
                </li>



            </ul>
        </nav>
    </div>
    <div class="container" style="padding-top: 50px;">

        {% block body_block %}


        {% endblock %}

    </div>


</body>

</html>

templates/banking/register.html
{% extends "base.html" %}
{% load static %}
{% block title_block %}Registration{% endblock %}

{% block css_block %}

<style>
    img {
        padding-top: 50px;
        width: 90%;
    }

    .container {
        margin-top: 45px;
    }

    .form-bg {
        background-color: rgb(156, 243, 236);
    }

    form {

        padding: 35px;
        border-color: white;
        border-width: 8px;
        border-style: double;
    }

    .form-group {
        padding-top: 10px;
    }

    label {
        font-weight: bold;
        padding-bottom: 5px;
    }
</style>

{% endblock %}


{% block body_block %}

{% include "navbar.html"%}

<div class="container ">
    <div class="row ">


        <div class="col-md-6 mx-auto p-5 form-bg  ">

            <form id="f" method="POST" action="">
                {% csrf_token %}
                <h1><b>Register Here!</b></h1>
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter your Name">
                </div>

                <div class="form-group">
                    <label for="email">Email Address:</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com">
                </div>

                <div class="form-group">
                    <label for="amount">Account Opening Amount:</label>
                    <input type="number" class="form-control" id="balance" name="balance"
                        placeholder="Enter Balance Amount">
                </div>



                <br>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>

        </div>



        <!-- <div class="col-sm-6">
            <img src="{%static 'images/registration.svg'%}" alt="">
        </div> -->


    </div>
</div>

{% endblock %}

templates/banking/user_details.html
{% extends "base.html" %}
{% load static %}
{% block title_block %}user details{% endblock %}

{% block css_block %}



{% endblock %}


{% block body_block %}

{% include "navbar.html"%}
<div class="container mt-5">
    <h1 class="text-center text-success p-2">Register User Information</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Balance</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <th scope="row">{{user.user_id}}</th>
                <td>{{user.name}}</td>
                <td>{{user.email}}</td>
                <td>${{user.balance}}</td>
            </tr>
            {% endfor %}


        </tbody>
    </table>
</div>

{% endblock %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title_block %} {% endblock %}</title>

    {% block css_block %}

    {% endblock %}

</head>

<body>


    {% block body_block %}


    {% endblock %}


    <footer class="text-muted footer ">
        <div class="container">
            <p class="text-center">&copy; Made by Nahid Hasan</p>
        </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

</body>

</html>

templates/navbar.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <title>{% block title_block %} {% endblock %}</title>
    {% block css_block %}
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap');
        font-family: 'Poppins',
        sans-serif;

        .nav-link {
            padding: 10px;
            font-size: 20px;
            font-weight: bold;
            color: black;
        }

        ul li {
            padding: 5px 15px;
        }

        a {
            text-decoration: none;
            color: black;
        }
    </style>

    {% endblock %}
</head>

<body>
    <div>

        <nav class=" navbar navbar-expand-md navbar-light bg-light">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a href="#" class="nav-link">
                        <h3 class="text-dark">BANGLADESH BANK</h3>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav m-auto">

                <li class="nav-item">

                    <h5 class="text-dark">
                        <a href="{% url 'banking:home'  %}">HOME</a>
                    </h5>
                </li>


                <li class="nav-item">
                    <h5 class="text-dark">
                        <a href="{% url 'banking:user_details'  %}">BANK USER</a>
                    </h5>
                </li>

                <li class="nav-item">
                    <a href="{% url 'banking:register'  %}">
                        <h5 class="text-dark">REGISTER</h5>
                    </a>

                </li>

            </ul>
        </nav>
    </div>
    <!-- <div class="container" style="padding-top: 50px;">

        {% block body_block %}


        {% endblock %}

    </div> -->


</body>

</html>

templates/transfer_history.html
{% extends "base.html" %}
{% load static %}
{% block title_block %}user details{% endblock %}

{% block css_block %}



{% endblock %}


{% block body_block %}

{% include "navbar.html"%}
<div class="container mt-5">
    <h1 class="text-center text-success p-2">Transfer Amount Transaction</h1>

    <table class="table table-striped">
        <thead>
            <tr>

                <th scope="col">Date</th>
                <th scope="col">Sender</th>
                <th scope="col">Receiver</th>
                <th scope="col">Amount</th>
            </tr>
        </thead>
        <tbody>
            {% for history in transfer_history %}
            <tr>
                <th scope="row">{{history.date}}</th>
                <td>{{history.sender}}</td>
                <td>{{history.receiver}}</td>
                <td>${{history.transfer_amount}}</td>
            </tr>
            {% endfor %}


        </tbody>
    </table>
</div>

{% endblock %}